### ISSUE TITLE
Changes With current style of writing the code. 

### ISSUE THREAD

**Issue by mHamza301** [iadnanmalik/typescript-guide#1]
There are some actionable points that I think should be addressed 

For example, `hello_1 `doesn't sound good, instead, `helloWithStringDeclaration` will be more descriptive about what the thing is.

Your functions names don't follow the proper convention of naming, either it should be camelCase or PascalCase, snake_case is used with other languages generally. JS/TS is most written in camelCase. 

Also, when you do something like `{ age : number }`  or `type : string` it shouldn't be like this. It should be `{ age: number }`  or `type: string`, so essentially we don't give space before colon only add a space after a colon.

**Comment by iadnanmalik** [comment]
Sounds good. Will change it accordingly
